### ISSUE TITLE
Update from Drupal 8.4.4 to 8.5.0 is not working for me

### ISSUE THREAD

**Issue by osopolar** [webflo/drupal-core-strict#5]
Am I doing something wrong? My composer.json file looks like:

```yml
{
    "name": "drupal/drupal",
    "description": "Drupal is an open source content management platform powering millions of websites and applications.",
    "type": "project",
    "license": "GPL-2.0+",
    "_readme": [
        "Use webflo/drupal-core-strict virtual package to ensure to get",
        "exactly the versions of Drupal core's dependencies as they are",
        "specified in Drupal core's composer.lock file"
    ],
    "require": {
        "drupal/core": "^8.5",
        "webflo/drupal-core-strict": "^8.5",
        "composer/installers": "^1.0.24",
        "wikimedia/composer-merge-plugin": "~1.4",
        "swiftmailer/swiftmailer": "^5.4",
        "html2text/html2text": "~4.0.1",
        "drupal-composer/drupal-scaffold": "dev-master",
        "tijsverkoyen/css-to-inline-styles": "^2.2"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "preferred-install": "dist",
        "autoloader-suffix": "Drupal8"
    },
    "extra": {
        "_readme": [
            "By default Drupal loads the autoloader from ./vendor/autoload.php.",
            "To change the autoloader you can edit ./autoload.php.",
            "This file specifies the packages.drupal.org repository.",
            "You can read more about this composer repository at:",
            "https://www.drupal.org/node/2718229"
        ],
        "merge-plugin": {
            "include": [
                "core/composer.json"
            ],
            "recurse": false,
            "replace": false,
            "merge-extra": false
        },
        "installer-paths": {
            "core": ["type:drupal-core"],
            "modules/contrib/{$name}": ["type:drupal-module"],
            "profiles/contrib/{$name}": ["type:drupal-profile"],
            "themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/contrib/{$name}": ["type:drupal-drush"],
            "modules/custom/{$name}": ["type:drupal-custom-module"],
            "themes/custom/{$name}": ["type:drupal-custom-theme"]
        }
    },
    "autoload": {
        "psr-4": {
            "Drupal\\Core\\Composer\\": "core/lib/Drupal/Core/Composer"
        }
    },
    "scripts": {
        "pre-autoload-dump": "Drupal\\Core\\Composer\\Composer::preAutoloadDump",
        "post-autoload-dump": [
          "Drupal\\Core\\Composer\\Composer::ensureHtaccess"
        ],
        "post-package-install": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup",
        "post-package-update": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ]
}
```

I tried to update drupal core with the following commands:

* composer update --no-dev
* composer update
* composer update --no-dev --with-dependencies
* composer update drupal/core webflo/drupal-core-strict --no-dev --with-dependencies
* composer update drupal/core webflo/drupal-core-strict

but none of these works. I always get the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - webflo/drupal-core-strict 8.6.x-dev requires symfony/class-loader v3.4.4 -> satisfiable by symfony/class-loader[v3.4.4] but these conflict with your requirements or minimum-stability.
    - webflo/drupal-core-strict 8.5.x-dev requires symfony/class-loader v3.4.4 -> satisfiable by symfony/class-loader[v3.4.4] but these conflict with your requirements or minimum-stability.
    - webflo/drupal-core-strict 8.5.0-rc1 requires symfony/class-loader v3.4.4 -> satisfiable by symfony/class-loader[v3.4.4] but these conflict with your requirements or minimum-stability.
    - webflo/drupal-core-strict 8.5.0-beta1 requires symfony/class-loader v3.4.4 -> satisfiable by symfony/class-loader[v3.4.4] but these conflict with your requirements or minimum-stability.
    - webflo/drupal-core-strict 8.5.0-alpha1 requires symfony/class-loader v3.4.3 -> satisfiable by symfony/class-loader[v3.4.3] but these conflict with your requirements or minimum-stability.
    - webflo/drupal-core-strict 8.5.0 requires symfony/class-loader v3.4.4 -> satisfiable by symfony/class-loader[v3.4.4] but these conflict with your requirements or minimum-stability.
    - Installation request for webflo/drupal-core-strict ^8.5 -> satisfiable by webflo/drupal-core-strict[8.5.0, 8.5.0-alpha1, 8.5.0-beta1, 8.5.0-rc1, 8.5.x-dev, 8.6.x-dev].
```

I also tried to change my composer.json file to:

        "drupal/core": "^8.5",
        "webflo/drupal-core-strict": "^8.5",

But it didn't work anyway. What did I miss?
